# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class Roll:
    r"""
    Python-facing dice roller.
    
    >>> from roller import Roll
    >>> r = Roll("4d6kh3")
    >>> r.total          # int
    >>> r.total_static   # int
    >>> r.rolls          # list[RollEntry]
    >>> r.code           # str
    >>> r.reroll()       # re-evaluate with fresh randomness
    """
    code: str
    total: int
    total_static: int
    rolls: list[RollEntry]
    def __new__(cls,die_code:str): ...
    def reroll(self) -> int:
        r"""
        Re-evaluate the roll with fresh randomness.
        """
        ...

    def __repr__(self) -> str:
        ...


class RollEntry:
    r"""
    A single dice-group result exposed to Python.
    """
    label: str
    details: list[int]
    def __repr__(self) -> str:
        ...


